# Generated by Django 5.1.7 on 2025-04-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluepay', '0003_virtualcard_card_type_virtualcard_default_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualcard',
            name='card_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='virtualcard',
            name='card_type',
            field=models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('american_express', 'American Express'), ('discover', 'Discover'), ('diners_club', 'Diners Club International'), ('jcb', 'JCB'), ('unionpay', 'UnionPay'), ('maestro', 'Maestro'), ('ru_pay', 'RuPay'), ('hipercard', 'Hipercard'), ('elo', 'Elo'), ('mir', 'MIR')], max_length=20, null=True),
        ),
    ]
