# Generated by Django 5.1.7 on 2025-08-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bluepay", "0005_alter_notification_notification_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="reference",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
