# Generated by Django 5.1.7 on 2025-04-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluepay', '0005_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency_code',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('TZS', 'Tanzanian Shilling')], default='USD', help_text='ISO 4217 currency code', max_length=3),
        ),
    ]
