# Generated by Django 5.1.7 on 2025-04-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluepay', '0006_transaction_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency_code',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('TZS', 'Tanzanian Shilling')], default='TZS', help_text='ISO 4217 currency code', max_length=3),
        ),
    ]
