# Generated by Django 5.1.6 on 2025-08-08 15:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0013_account_daily_limit_account_monthly_limit_and_more"),
        ("bluepay", "0007_mobilemoneyprovider_payment_transaction_payment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payout_reference", models.CharField(max_length=100, unique=True)),
                ("order_reference", models.CharField(max_length=100, unique=True)),
                (
                    "clickpesa_payout_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("payout_type", models.CharField(default="WITHDRAWAL", max_length=20)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                        ],
                        default="MOBILE_MONEY",
                        max_length=20,
                    ),
                ),
                (
                    "channel_provider",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="TZS", max_length=10)),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AUTHORIZED", "Authorized"),
                            ("SUCCESS", "Success"),
                            ("PROCESSING", "Processing"),
                            ("PENDING", "Pending"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                            ("REVERSED", "Reversed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("beneficiary_name", models.CharField(max_length=200)),
                ("beneficiary_phone", models.CharField(max_length=20)),
                (
                    "beneficiary_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("client_id", models.CharField(blank=True, max_length=100, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("preview_data", models.JSONField(blank=True, default=dict)),
                (
                    "payout_fee_bearer",
                    models.CharField(default="customer", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("clickpesa_created_at", models.DateTimeField(blank=True, null=True)),
                ("clickpesa_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="Accounts.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayoutStatusHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AUTHORIZED", "Authorized"),
                            ("SUCCESS", "Success"),
                            ("PROCESSING", "Processing"),
                            ("PENDING", "Pending"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                            ("REVERSED", "Reversed"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("AUTHORIZED", "Authorized"),
                            ("SUCCESS", "Success"),
                            ("PROCESSING", "Processing"),
                            ("PENDING", "Pending"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                            ("REVERSED", "Reversed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="bluepay.payout",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PayoutWebhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order_reference", models.CharField(max_length=100)),
                ("webhook_data", models.JSONField()),
                ("processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payout",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="bluepay.payout",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="payout",
            index=models.Index(
                fields=["order_reference"], name="bluepay_pay_order_r_a39404_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payout",
            index=models.Index(
                fields=["payout_reference"], name="bluepay_pay_payout__9d22a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payout",
            index=models.Index(fields=["status"], name="bluepay_pay_status_275721_idx"),
        ),
        migrations.AddIndex(
            model_name="payout",
            index=models.Index(
                fields=["account", "status"], name="bluepay_pay_account_784700_idx"
            ),
        ),
    ]
