# Generated by Django 5.1.7 on 2025-04-29 22:20

import shortuuid.django_fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluepay', '0007_alter_transaction_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='txn_type',
            field=models.CharField(choices=[('top_up', 'Top Up'), ('withdraw', 'Withdraw'), ('nfc_pay', 'NFC Payment'), ('none', 'None')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='virtualcard',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymenttoken',
            name='token',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=20, max_length=23, prefix='TAP', unique=True),
        ),
    ]
