# Generated by Django 5.1.7 on 2025-04-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluepay', '0008_transaction_txn_type_virtualcard_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='txn_type',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='txn_type',
            field=models.CharField(choices=[('top_up', 'Top Up'), ('withdraw', 'Withdraw'), ('nfc_pay', 'NFC Payment'), ('none', 'None')], default='none', max_length=10),
        ),
    ]
