# Generated by Django 5.1.7 on 2025-04-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluepay', '0009_remove_paymenttransaction_transaction_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('refund', 'Refund'), ('transfer', 'Transfer')], default='purchase', max_length=20),
        ),
    ]
