# Generated by Django 5.1.7 on 2025-04-30 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluepay', '0010_paymenttransaction_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general', models.BooleanField(default=True)),
                ('sound', models.BooleanField(default=False)),
                ('vibrate', models.BooleanField(default=False)),
                ('app_updates', models.BooleanField(default=True)),
                ('bill_reminder', models.BooleanField(default=True)),
                ('promotion', models.BooleanField(default=False)),
                ('discounts', models.BooleanField(default=False)),
                ('payment_request', models.BooleanField(default=True)),
                ('new_service', models.BooleanField(default=False)),
                ('new_tips', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notification Settings',
            },
        ),
    ]
