# Generated by Django 5.1.7 on 2025-04-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluepay', '0011_notificationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('None', 'None'), ('Transfer', 'Transfer'), ('Credit Alert', 'Credit Alert'), ('Debit Alert', 'Debit Alert'), ('Sent Payment Request', 'Sent Payment Request'), ('Recieved Payment Request', 'Recieved Payment Request'), ('Funded Credit Card', 'Funded Credit Card'), ('Withdrew Credit Card Funds', 'Withdrew Credit Card Funds'), ('Deleted Credit Card', 'Deleted Credit Card'), ('Added Credit Card', 'Added Credit Card'), ('Updated Credit Card', 'Updated Credit Card'), ('top_up_initiated', 'Top-Up Initiated'), ('top_up_success', 'Top-Up Successful'), ('top_up_failed', 'Top-Up Failed'), ('withdrawal_initiated', 'Withdrawal Initiated'), ('withdrawal_success', 'Withdrawal Successful'), ('withdrawal_failed', 'Withdrawal Failed'), ('payment_initiated', 'Payment Initiated'), ('payment_success', 'Payment Successful'), ('payment_failed', 'Payment Failed'), ('transfer_initiated', 'Transfer Initiated'), ('transfer_success', 'Transfer Successful'), ('transfer_failed', 'Transfer Failed'), ('refund_initiated', 'Refund Initiated'), ('refund_success', 'Refund Processed'), ('refund_failed', 'Refund Failed'), ('nfc_tap_success', 'NFC Tap Successful'), ('nfc_tap_failed', 'NFC Tap Failed'), ('contactless_success', 'Contactless Payment Successful'), ('contactless_failed', 'Contactless Payment Declined'), ('balance_low_alert', 'Low Balance Alert'), ('balance_updated', 'Balance Updated'), ('daily_summary_ready', 'Daily Summary Ready'), ('monthly_statement_ready', 'Monthly Statement Ready'), ('new_device_login', 'New Device Login Detected'), ('password_changed', 'Password Changed'), ('pin_changed', 'PIN Changed'), ('suspicious_activity', 'Suspicious Activity Alert'), ('fraud_alert', 'Fraud Alert'), ('kyc_submitted', 'KYC Submitted'), ('kyc_approved', 'KYC Approved'), ('kyc_rejected', 'KYC Rejected'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked'), ('promo_offer', 'New Promotional Offer'), ('discount_available', 'Discount Available'), ('app_update_available', 'App Update Available')], default='none', max_length=100),
        ),
    ]
