# Generated by Django 5.1.7 on 2025-04-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluepay', '0013_deactivationreason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeactivationReason',
        ),
    ]
