# Generated by Django 5.1.7 on 2025-04-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluepay', '0014_delete_deactivationreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
