# Generated by Django 5.1.7 on 2025-04-30 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluepay', '0015_notification_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remember_me', models.BooleanField(default=True)),
                ('face_id', models.BooleanField(default=False)),
                ('biometric_id', models.BooleanField(default=False)),
                ('ga_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('ga_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_setting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
