# Generated by Django 5.1.7 on 2025-05-04 12:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluepay', '0016_securitysetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('api_endpoint', models.URLField(help_text='External API endpoint for this biller')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('compliance_type', models.CharField(choices=[('pci_dss', 'PCI-DSS'), ('emvco', 'EMVCo')], max_length=20)),
                ('level', models.CharField(help_text='Merchant or service level, e.g., Level 1', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('compliant', 'Compliant'), ('non_compliant', 'Non-Compliant')], default='pending', max_length=20)),
                ('last_audit_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='nfcdevice',
            name='device_fingerprint',
            field=models.CharField(blank=True, help_text='Fingerprint for binding', max_length=255),
        ),
        migrations.AddField(
            model_name='nfcdevice',
            name='is_bound',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nfcdevice',
            name='last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nfcdevice',
            name='os_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='paymenttoken',
            name='provider',
            field=models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('american_express', 'American Express'), ('discover', 'Discover'), ('diners_club', 'Diners Club International'), ('jcb', 'JCB'), ('unionpay', 'UnionPay'), ('maestro', 'Maestro'), ('ru_pay', 'RuPay'), ('hipercard', 'Hipercard'), ('elo', 'Elo'), ('mir', 'MIR')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='risk_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='risk_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='virtualcard',
            name='token_provider',
            field=models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('american_express', 'American Express'), ('discover', 'Discover'), ('diners_club', 'Diners Club International'), ('jcb', 'JCB'), ('unionpay', 'UnionPay'), ('maestro', 'Maestro'), ('ru_pay', 'RuPay'), ('hipercard', 'Hipercard'), ('elo', 'Elo'), ('mir', 'MIR')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='virtualcard',
            name='token_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('revoked', 'Revoked')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='EMVToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_reference', models.CharField(max_length=255, unique=True)),
                ('provider', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('american_express', 'American Express'), ('discover', 'Discover'), ('diners_club', 'Diners Club International'), ('jcb', 'JCB'), ('unionpay', 'UnionPay'), ('maestro', 'Maestro'), ('ru_pay', 'RuPay'), ('hipercard', 'Hipercard'), ('elo', 'Elo'), ('mir', 'MIR')], max_length=50)),
                ('status', models.CharField(choices=[('provisioned', 'Provisioned'), ('activated', 'Activated'), ('deactivated', 'Deactivated')], default='provisioned', max_length=20)),
                ('provisioned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('virtual_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emv_tokens', to='bluepay.virtualcard')),
            ],
        ),
    ]
