# Generated by Django 5.1.7 on 2025-03-27 11:14

import django.db.models.deletion
import userAccount.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(default=userAccount.models.generate_otp, max_length=6)),
                ('purpose', models.CharField(choices=[('registration', 'Registration'), ('login', 'Login')], default='registration', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
