# Generated by Django 5.1.7 on 2025-04-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0002_otpverification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otpverification',
            options={'verbose_name': 'OTP VERIFICATION', 'verbose_name_plural': 'OTP VERIFICATIONS'},
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('registration', 'Registration'), ('login', 'Login'), ('forgot_password', 'Forgot Password')], default='registration', max_length=20),
        ),
    ]
