# Generated by Django 5.1.7 on 2025-04-30 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0003_alter_otpverification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeactivationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('not_useful', 'The service is not useful to me'), ('too_expensive', 'It is too expensive'), ('technical_issues', 'I experienced technical issues'), ('privacy_concerns', 'I have privacy concerns'), ('found_alternative', 'I found a better alternative'), ('other', 'Other')], max_length=50)),
                ('other_reason', models.TextField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
