# Generated by Django 5.1.7 on 2025-04-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccount', '0004_deactivationreason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deactivationreason',
            name='reason',
            field=models.CharField(choices=[('not_accepted_widely', 'The payment system is not accepted at many locations'), ('security_concerns', 'I have concerns about payment security or data privacy'), ('technical_glitches', 'I encountered frequent technical issues or failed transactions'), ('switched_provider', 'I switched to a different payment provider'), ('limited_features', 'The system lacks features I need'), ('other', 'Other (please specify)')], max_length=50),
        ),
    ]
