# Generated by Django 5.1.7 on 2025-04-02 15:16

import Accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kyc',
            options={'ordering': ['-date'], 'verbose_name': 'KYC Record', 'verbose_name_plural': 'KYC Records'},
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='image',
        ),
        migrations.AddField(
            model_name='kyc',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kyc',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kyc',
            name='face_verification_image',
            field=models.ImageField(blank=True, help_text='Image used for face verification', null=True, upload_to=Accounts.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='kyc',
            name='profile_image',
            field=models.ImageField(default='default.jpg', help_text='A clear picture of your face', upload_to=Accounts.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='kyc',
            name='tree_name',
            field=models.CharField(blank=True, help_text='Optional: Enter your family or traditional name if applicable', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='identity_type',
            field=models.CharField(choices=[('national_id_card', 'National ID Card'), ('drivers_licence', 'Drivers Licence'), ('international_passport', 'International Passport')], max_length=50),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=Accounts.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
