# Generated by Django 5.1.7 on 2025-04-02 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_kyc_options_remove_kyc_image_kyc_address_line1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='tree_name',
            new_name='Last_name',
        ),
    ]
