# Generated by Django 5.1.7 on 2025-04-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_rename_full_name_kyc_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='signature',
        ),
        migrations.AddField(
            model_name='kyc',
            name='biometric_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of the face verification image', max_length=64, null=True),
        ),
    ]
