# Generated by Django 5.1.7 on 2025-04-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_remove_kyc_signature_kyc_biometric_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
