# Generated by Django 5.1.7 on 2025-04-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_alter_kyc_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kyc',
            old_name='face_verification_image',
            new_name='selfie_image',
        ),
        migrations.AddField(
            model_name='kyc',
            name='face_match_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='face_verified',
            field=models.BooleanField(default=False),
        ),
    ]
