# Generated by Django 5.1.7 on 2025-04-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_rename_face_verification_image_kyc_selfie_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='fax',
        ),
    ]
