# Generated by Django 5.1.7 on 2025-04-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0009_remove_kyc_fax'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fingerprint_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='fingerprint_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
