# Generated by Django 5.1.7 on 2025-04-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_account_fingerprint_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='faceid_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='faceid_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
