# Generated by Django 5.1.7 on 2025-04-28 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_account_faceid_enabled_account_faceid_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='default_currency_code',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('TZS', 'Tanzanian Shilling')], default='TZS', help_text='ISO 4217 currency code for this account', max_length=3),
        ),
    ]
