# Generated by Django 5.1.7 on 2025-07-21 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_account_faceid_enabled_account_faceid_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='Accounts.account'),
        ),
    ]
