# Generated by Django 5.1.7 on 2025-04-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_account_default_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='The Stripe Customer ID for this account', max_length=255, null=True),
        ),
    ]
