# Generated by Django 5.1.6 on 2025-08-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0012_alter_kyc_account"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="daily_limit",
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="account",
            name="monthly_limit",
            field=models.DecimalField(
                decimal_places=2, default=200000.0, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="single_transaction_limit",
            field=models.DecimalField(decimal_places=2, default=20000.0, max_digits=12),
        ),
    ]
