# Generated by Django 5.1.7 on 2025-04-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_account_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
