# Generated by Django 5.1.7 on 2025-05-04 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0014_account_pin_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_number',
        ),
    ]
